// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: contactical/reality/v1/claim.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Claim defines the Claim message.
type Claim struct {
	Id              uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SensorHash      string `protobuf:"bytes,2,opt,name=sensor_hash,json=sensorHash,proto3" json:"sensor_hash,omitempty"`
	GnssHash        string `protobuf:"bytes,3,opt,name=gnss_hash,json=gnssHash,proto3" json:"gnss_hash,omitempty"`
	AnchorSignature string `protobuf:"bytes,4,opt,name=anchor_signature,json=anchorSignature,proto3" json:"anchor_signature,omitempty"`
	Creator         string `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	TrustLevel      string `protobuf:"bytes,6,opt,name=trust_level,json=trustLevel,proto3" json:"trust_level,omitempty"`
	// [수정] bytes -> string (Base64 호환성)
	DataSignature    string `protobuf:"bytes,7,opt,name=data_signature,json=dataSignature,proto3" json:"data_signature,omitempty"`
	TrustScore       int32  `protobuf:"varint,8,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`
	RewardMultiplier int32  `protobuf:"varint,9,opt,name=reward_multiplier,json=rewardMultiplier,proto3" json:"reward_multiplier,omitempty"`
}

func (m *Claim) Reset()         { *m = Claim{} }
func (m *Claim) String() string { return proto.CompactTextString(m) }
func (*Claim) ProtoMessage()    {}
func (*Claim) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3af3642db6b9da9, []int{0}
}
func (m *Claim) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Claim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Claim.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Claim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Claim.Merge(m, src)
}
func (m *Claim) XXX_Size() int {
	return m.Size()
}
func (m *Claim) XXX_DiscardUnknown() {
	xxx_messageInfo_Claim.DiscardUnknown(m)
}

var xxx_messageInfo_Claim proto.InternalMessageInfo

func (m *Claim) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Claim) GetSensorHash() string {
	if m != nil {
		return m.SensorHash
	}
	return ""
}

func (m *Claim) GetGnssHash() string {
	if m != nil {
		return m.GnssHash
	}
	return ""
}

func (m *Claim) GetAnchorSignature() string {
	if m != nil {
		return m.AnchorSignature
	}
	return ""
}

func (m *Claim) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Claim) GetTrustLevel() string {
	if m != nil {
		return m.TrustLevel
	}
	return ""
}

func (m *Claim) GetDataSignature() string {
	if m != nil {
		return m.DataSignature
	}
	return ""
}

func (m *Claim) GetTrustScore() int32 {
	if m != nil {
		return m.TrustScore
	}
	return 0
}

func (m *Claim) GetRewardMultiplier() int32 {
	if m != nil {
		return m.RewardMultiplier
	}
	return 0
}

func init() {
	proto.RegisterType((*Claim)(nil), "contactical.reality.v1.Claim")
}

func init() {
	proto.RegisterFile("contactical/reality/v1/claim.proto", fileDescriptor_e3af3642db6b9da9)
}

var fileDescriptor_e3af3642db6b9da9 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0x9b, 0xb5, 0x7f, 0x23, 0xd6, 0x9a, 0x83, 0x04, 0x0a, 0x6b, 0x29, 0x08, 0x15, 0xa1,
	0xa5, 0x88, 0x2f, 0xa0, 0x17, 0x0f, 0x7a, 0x69, 0x6f, 0x5e, 0x96, 0x31, 0x1b, 0xba, 0x81, 0x74,
	0x53, 0x26, 0x69, 0xb5, 0x6f, 0xe1, 0xa3, 0xf8, 0x18, 0x1e, 0x7b, 0xf4, 0x28, 0xed, 0x8b, 0x48,
	0xb2, 0x6d, 0xdd, 0xe3, 0xfc, 0xbe, 0x1f, 0x33, 0x03, 0x1f, 0xed, 0x0b, 0x93, 0x3b, 0x10, 0x4e,
	0x09, 0xd0, 0x23, 0x94, 0xa0, 0x95, 0x5b, 0x8f, 0x56, 0xe3, 0x91, 0xd0, 0xa0, 0xe6, 0xc3, 0x05,
	0x1a, 0x67, 0xd8, 0x65, 0xc9, 0x19, 0xee, 0x9d, 0xe1, 0x6a, 0xdc, 0xff, 0x8a, 0x68, 0xed, 0xd1,
	0x7b, 0xac, 0x4d, 0x23, 0x95, 0x72, 0xd2, 0x23, 0x83, 0xea, 0x24, 0x52, 0x29, 0xbb, 0xa2, 0xa7,
	0x56, 0xe6, 0xd6, 0x60, 0x92, 0x81, 0xcd, 0x78, 0xd4, 0x23, 0x83, 0xd6, 0x84, 0x16, 0xe8, 0x09,
	0x6c, 0xc6, 0xba, 0xb4, 0x35, 0xcb, 0xad, 0x2d, 0xe2, 0x93, 0x10, 0x37, 0x3d, 0x08, 0xe1, 0x0d,
	0xed, 0x40, 0x2e, 0x32, 0x83, 0x89, 0x55, 0xb3, 0x1c, 0xdc, 0x12, 0x25, 0xaf, 0x06, 0xe7, 0xbc,
	0xe0, 0xd3, 0x03, 0x66, 0x9c, 0x36, 0x04, 0x4a, 0x70, 0x06, 0x79, 0x2d, 0x18, 0x87, 0xd1, 0xbf,
	0xe0, 0x70, 0x69, 0x5d, 0xa2, 0xe5, 0x4a, 0x6a, 0x5e, 0x2f, 0x5e, 0x08, 0xe8, 0xd9, 0x13, 0x76,
	0x4d, 0xdb, 0x29, 0x38, 0x28, 0xdd, 0x68, 0x04, 0xe7, 0xcc, 0xd3, 0xff, 0x0b, 0xc7, 0x3d, 0x56,
	0x18, 0x94, 0xbc, 0xd9, 0x23, 0x83, 0xda, 0x7e, 0xcf, 0xd4, 0x13, 0x76, 0x4b, 0x2f, 0x50, 0xbe,
	0x03, 0xa6, 0xc9, 0x7c, 0xa9, 0x9d, 0x5a, 0x68, 0x25, 0x91, 0xb7, 0x82, 0xd6, 0x29, 0x82, 0x97,
	0x23, 0x7f, 0xb8, 0xff, 0xde, 0xc6, 0x64, 0xb3, 0x8d, 0xc9, 0xef, 0x36, 0x26, 0x9f, 0xbb, 0xb8,
	0xb2, 0xd9, 0xc5, 0x95, 0x9f, 0x5d, 0x5c, 0x79, 0xed, 0x96, 0x8b, 0xf8, 0x38, 0x56, 0xe1, 0xd6,
	0x0b, 0x69, 0xdf, 0xea, 0xa1, 0x88, 0xbb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x86, 0xd4,
	0xc7, 0xae, 0x01, 0x00, 0x00,
}

func (m *Claim) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Claim) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Claim) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RewardMultiplier != 0 {
		i = encodeVarintClaim(dAtA, i, uint64(m.RewardMultiplier))
		i--
		dAtA[i] = 0x48
	}
	if m.TrustScore != 0 {
		i = encodeVarintClaim(dAtA, i, uint64(m.TrustScore))
		i--
		dAtA[i] = 0x40
	}
	if len(m.DataSignature) > 0 {
		i -= len(m.DataSignature)
		copy(dAtA[i:], m.DataSignature)
		i = encodeVarintClaim(dAtA, i, uint64(len(m.DataSignature)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.TrustLevel) > 0 {
		i -= len(m.TrustLevel)
		copy(dAtA[i:], m.TrustLevel)
		i = encodeVarintClaim(dAtA, i, uint64(len(m.TrustLevel)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintClaim(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.AnchorSignature) > 0 {
		i -= len(m.AnchorSignature)
		copy(dAtA[i:], m.AnchorSignature)
		i = encodeVarintClaim(dAtA, i, uint64(len(m.AnchorSignature)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.GnssHash) > 0 {
		i -= len(m.GnssHash)
		copy(dAtA[i:], m.GnssHash)
		i = encodeVarintClaim(dAtA, i, uint64(len(m.GnssHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SensorHash) > 0 {
		i -= len(m.SensorHash)
		copy(dAtA[i:], m.SensorHash)
		i = encodeVarintClaim(dAtA, i, uint64(len(m.SensorHash)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintClaim(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintClaim(dAtA []byte, offset int, v uint64) int {
	offset -= sovClaim(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Claim) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovClaim(uint64(m.Id))
	}
	l = len(m.SensorHash)
	if l > 0 {
		n += 1 + l + sovClaim(uint64(l))
	}
	l = len(m.GnssHash)
	if l > 0 {
		n += 1 + l + sovClaim(uint64(l))
	}
	l = len(m.AnchorSignature)
	if l > 0 {
		n += 1 + l + sovClaim(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovClaim(uint64(l))
	}
	l = len(m.TrustLevel)
	if l > 0 {
		n += 1 + l + sovClaim(uint64(l))
	}
	l = len(m.DataSignature)
	if l > 0 {
		n += 1 + l + sovClaim(uint64(l))
	}
	if m.TrustScore != 0 {
		n += 1 + sovClaim(uint64(m.TrustScore))
	}
	if m.RewardMultiplier != 0 {
		n += 1 + sovClaim(uint64(m.RewardMultiplier))
	}
	return n
}

func sovClaim(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozClaim(x uint64) (n int) {
	return sovClaim(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Claim) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClaim
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Claim: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Claim: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClaim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SensorHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClaim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClaim
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClaim
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SensorHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GnssHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClaim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClaim
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClaim
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GnssHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AnchorSignature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClaim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClaim
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClaim
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AnchorSignature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClaim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClaim
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClaim
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustLevel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClaim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClaim
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClaim
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrustLevel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataSignature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClaim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClaim
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClaim
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataSignature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustScore", wireType)
			}
			m.TrustScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClaim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrustScore |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardMultiplier", wireType)
			}
			m.RewardMultiplier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClaim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RewardMultiplier |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipClaim(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClaim
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipClaim(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowClaim
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClaim
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClaim
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthClaim
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupClaim
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthClaim
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthClaim        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowClaim          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupClaim = fmt.Errorf("proto: unexpected end of group")
)
