// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: contactical/reality/v1/node.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// NodeInfo stores attestation information for a registered node
type NodeInfo struct {
	Creator          string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	SecurityLevel    int32  `protobuf:"varint,2,opt,name=security_level,json=securityLevel,proto3" json:"security_level,omitempty"`
	DeviceLocked     bool   `protobuf:"varint,3,opt,name=device_locked,json=deviceLocked,proto3" json:"device_locked,omitempty"`
	BootState        int32  `protobuf:"varint,4,opt,name=boot_state,json=bootState,proto3" json:"boot_state,omitempty"`
	CreationTime     int64  `protobuf:"varint,5,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	AttestationLevel int32  `protobuf:"varint,6,opt,name=attestation_level,json=attestationLevel,proto3" json:"attestation_level,omitempty"`
	OsVersion        int32  `protobuf:"varint,7,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	OsPatchLevel     int32  `protobuf:"varint,8,opt,name=os_patch_level,json=osPatchLevel,proto3" json:"os_patch_level,omitempty"`
	RegisteredAt     int64  `protobuf:"varint,9,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	// [수정] bytes -> string
	PubKey string `protobuf:"bytes,10,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf075aa1a80a4bf4, []int{0}
}
func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return m.Size()
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *NodeInfo) GetSecurityLevel() int32 {
	if m != nil {
		return m.SecurityLevel
	}
	return 0
}

func (m *NodeInfo) GetDeviceLocked() bool {
	if m != nil {
		return m.DeviceLocked
	}
	return false
}

func (m *NodeInfo) GetBootState() int32 {
	if m != nil {
		return m.BootState
	}
	return 0
}

func (m *NodeInfo) GetCreationTime() int64 {
	if m != nil {
		return m.CreationTime
	}
	return 0
}

func (m *NodeInfo) GetAttestationLevel() int32 {
	if m != nil {
		return m.AttestationLevel
	}
	return 0
}

func (m *NodeInfo) GetOsVersion() int32 {
	if m != nil {
		return m.OsVersion
	}
	return 0
}

func (m *NodeInfo) GetOsPatchLevel() int32 {
	if m != nil {
		return m.OsPatchLevel
	}
	return 0
}

func (m *NodeInfo) GetRegisteredAt() int64 {
	if m != nil {
		return m.RegisteredAt
	}
	return 0
}

func (m *NodeInfo) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeInfo)(nil), "contactical.reality.v1.NodeInfo")
}

func init() { proto.RegisterFile("contactical/reality/v1/node.proto", fileDescriptor_cf075aa1a80a4bf4) }

var fileDescriptor_cf075aa1a80a4bf4 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xcd, 0xaa, 0xd3, 0x40,
	0x14, 0xc7, 0x3b, 0xad, 0xfd, 0x1a, 0xda, 0xa2, 0xb3, 0xd0, 0x01, 0x69, 0x88, 0x5f, 0x10, 0x10,
	0x5a, 0x8a, 0xf8, 0x00, 0xba, 0x13, 0x8b, 0x48, 0x14, 0x17, 0x6e, 0x86, 0xc9, 0xe4, 0xa8, 0x43,
	0xd3, 0x9c, 0x30, 0x73, 0x1a, 0xcc, 0x5b, 0xf8, 0x58, 0x2e, 0xbb, 0xbc, 0xcb, 0x4b, 0x7b, 0x1f,
	0xe4, 0x92, 0xa4, 0xed, 0xed, 0x72, 0x7e, 0xf3, 0xe7, 0x77, 0xce, 0xcc, 0x9f, 0xbf, 0x30, 0x98,
	0x93, 0x36, 0x64, 0x8d, 0xce, 0x96, 0x0e, 0x74, 0x66, 0xa9, 0x5a, 0x96, 0xab, 0x65, 0x8e, 0x29,
	0x2c, 0x0a, 0x87, 0x84, 0xe2, 0xe9, 0x55, 0x64, 0x71, 0x8a, 0x2c, 0xca, 0xd5, 0xcb, 0xbb, 0x2e,
	0x1f, 0x7d, 0xc1, 0x14, 0x3e, 0xe5, 0xbf, 0x50, 0x48, 0x3e, 0x34, 0x0e, 0x34, 0xa1, 0x93, 0x2c,
	0x64, 0xd1, 0x38, 0x3e, 0x1f, 0xc5, 0x1b, 0x3e, 0xf3, 0x60, 0x76, 0xce, 0x52, 0xa5, 0x32, 0x28,
	0x21, 0x93, 0xdd, 0x90, 0x45, 0xfd, 0x78, 0x7a, 0xa6, 0xeb, 0x1a, 0x8a, 0x57, 0x7c, 0x9a, 0x42,
	0x69, 0x0d, 0xa8, 0x0c, 0xcd, 0x06, 0x52, 0xd9, 0x0b, 0x59, 0x34, 0x8a, 0x27, 0x2d, 0x5c, 0x37,
	0x4c, 0xcc, 0x39, 0x4f, 0x10, 0x49, 0x79, 0xd2, 0x04, 0xf2, 0x51, 0xe3, 0x19, 0xd7, 0xe4, 0x5b,
	0x0d, 0x6a, 0x47, 0x33, 0xd5, 0x62, 0xae, 0xc8, 0x6e, 0x41, 0xf6, 0x43, 0x16, 0xf5, 0xe2, 0xc9,
	0x19, 0x7e, 0xb7, 0x5b, 0x10, 0x6f, 0xf9, 0x13, 0x4d, 0x04, 0xb5, 0xa2, 0xce, 0xb5, 0x2b, 0x0d,
	0x1a, 0xd5, 0xe3, 0xab, 0x8b, 0x76, 0xab, 0x39, 0xe7, 0xe8, 0x55, 0x09, 0xce, 0x5b, 0xcc, 0xe5,
	0xb0, 0x1d, 0x88, 0xfe, 0x47, 0x0b, 0xc4, 0x6b, 0x3e, 0x43, 0xaf, 0x0a, 0x4d, 0xe6, 0xcf, 0x49,
	0x34, 0x6a, 0x22, 0x13, 0xf4, 0x5f, 0x6b, 0x78, 0x79, 0x9a, 0x83, 0xdf, 0xd6, 0x13, 0x38, 0x48,
	0x95, 0x26, 0x39, 0x6e, 0xd7, 0x7a, 0x80, 0x1f, 0x48, 0x3c, 0xe3, 0xc3, 0x62, 0x97, 0xa8, 0x0d,
	0x54, 0x92, 0x37, 0x1f, 0x38, 0x28, 0x76, 0xc9, 0x67, 0xa8, 0x3e, 0xbe, 0xff, 0x7f, 0x08, 0xd8,
	0xfe, 0x10, 0xb0, 0xdb, 0x43, 0xc0, 0xfe, 0x1d, 0x83, 0xce, 0xfe, 0x18, 0x74, 0x6e, 0x8e, 0x41,
	0xe7, 0xe7, 0xf3, 0xeb, 0xee, 0xfe, 0x5e, 0xda, 0xa3, 0xaa, 0x00, 0x9f, 0x0c, 0x9a, 0xf2, 0xde,
	0xdd, 0x07, 0x00, 0x00, 0xff, 0xff, 0x09, 0xb7, 0x08, 0xe8, 0xe1, 0x01, 0x00, 0x00,
}

func (m *NodeInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PubKey) > 0 {
		i -= len(m.PubKey)
		copy(dAtA[i:], m.PubKey)
		i = encodeVarintNode(dAtA, i, uint64(len(m.PubKey)))
		i--
		dAtA[i] = 0x52
	}
	if m.RegisteredAt != 0 {
		i = encodeVarintNode(dAtA, i, uint64(m.RegisteredAt))
		i--
		dAtA[i] = 0x48
	}
	if m.OsPatchLevel != 0 {
		i = encodeVarintNode(dAtA, i, uint64(m.OsPatchLevel))
		i--
		dAtA[i] = 0x40
	}
	if m.OsVersion != 0 {
		i = encodeVarintNode(dAtA, i, uint64(m.OsVersion))
		i--
		dAtA[i] = 0x38
	}
	if m.AttestationLevel != 0 {
		i = encodeVarintNode(dAtA, i, uint64(m.AttestationLevel))
		i--
		dAtA[i] = 0x30
	}
	if m.CreationTime != 0 {
		i = encodeVarintNode(dAtA, i, uint64(m.CreationTime))
		i--
		dAtA[i] = 0x28
	}
	if m.BootState != 0 {
		i = encodeVarintNode(dAtA, i, uint64(m.BootState))
		i--
		dAtA[i] = 0x20
	}
	if m.DeviceLocked {
		i--
		if m.DeviceLocked {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.SecurityLevel != 0 {
		i = encodeVarintNode(dAtA, i, uint64(m.SecurityLevel))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintNode(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintNode(dAtA []byte, offset int, v uint64) int {
	offset -= sovNode(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NodeInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovNode(uint64(l))
	}
	if m.SecurityLevel != 0 {
		n += 1 + sovNode(uint64(m.SecurityLevel))
	}
	if m.DeviceLocked {
		n += 2
	}
	if m.BootState != 0 {
		n += 1 + sovNode(uint64(m.BootState))
	}
	if m.CreationTime != 0 {
		n += 1 + sovNode(uint64(m.CreationTime))
	}
	if m.AttestationLevel != 0 {
		n += 1 + sovNode(uint64(m.AttestationLevel))
	}
	if m.OsVersion != 0 {
		n += 1 + sovNode(uint64(m.OsVersion))
	}
	if m.OsPatchLevel != 0 {
		n += 1 + sovNode(uint64(m.OsPatchLevel))
	}
	if m.RegisteredAt != 0 {
		n += 1 + sovNode(uint64(m.RegisteredAt))
	}
	l = len(m.PubKey)
	if l > 0 {
		n += 1 + l + sovNode(uint64(l))
	}
	return n
}

func sovNode(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNode(x uint64) (n int) {
	return sovNode(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NodeInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNode
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNode
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNode
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecurityLevel", wireType)
			}
			m.SecurityLevel = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SecurityLevel |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceLocked", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DeviceLocked = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BootState", wireType)
			}
			m.BootState = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BootState |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationTime", wireType)
			}
			m.CreationTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreationTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationLevel", wireType)
			}
			m.AttestationLevel = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AttestationLevel |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OsVersion", wireType)
			}
			m.OsVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OsVersion |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OsPatchLevel", wireType)
			}
			m.OsPatchLevel = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OsPatchLevel |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredAt", wireType)
			}
			m.RegisteredAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegisteredAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNode
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNode
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNode
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNode(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNode
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNode(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNode
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNode
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNode
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNode
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNode
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNode
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNode        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNode          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNode = fmt.Errorf("proto: unexpected end of group")
)
