// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: contactical/reality/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params는 reality 모듈의 매개변수를 정의합니다.
type Params struct {
	// 보상 계산의 기본 단위 (기존 1000)
	RewardBaseUnit int64 `protobuf:"varint,1,opt,name=reward_base_unit,json=rewardBaseUnit,proto3" json:"reward_base_unit,omitempty"`
	// StrongBox 가산점 (기존 50)
	BonusStrongbox int32 `protobuf:"varint,2,opt,name=bonus_strongbox,json=bonusStrongbox,proto3" json:"bonus_strongbox,omitempty"`
	// 일반 TEE 가산점 (기존 30)
	BonusTee int32 `protobuf:"varint,3,opt,name=bonus_tee,json=bonusTee,proto3" json:"bonus_tee,omitempty"`
	// 부트 락(Verified Boot) 가산점 (기존 10)
	BonusBootLock int32 `protobuf:"varint,4,opt,name=bonus_boot_lock,json=bonusBootLock,proto3" json:"bonus_boot_lock,omitempty"`
	// 주변 노드당 밀집도 가산점 (기존 20)
	BonusDensityPerNode int32 `protobuf:"varint,5,opt,name=bonus_density_per_node,json=bonusDensityPerNode,proto3" json:"bonus_density_per_node,omitempty"`
	// 최대 신뢰 점수 제한 (기존 100)
	MaxTrustScore int32 `protobuf:"varint,6,opt,name=max_trust_score,json=maxTrustScore,proto3" json:"max_trust_score,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6500cda98d68c26f, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetRewardBaseUnit() int64 {
	if m != nil {
		return m.RewardBaseUnit
	}
	return 0
}

func (m *Params) GetBonusStrongbox() int32 {
	if m != nil {
		return m.BonusStrongbox
	}
	return 0
}

func (m *Params) GetBonusTee() int32 {
	if m != nil {
		return m.BonusTee
	}
	return 0
}

func (m *Params) GetBonusBootLock() int32 {
	if m != nil {
		return m.BonusBootLock
	}
	return 0
}

func (m *Params) GetBonusDensityPerNode() int32 {
	if m != nil {
		return m.BonusDensityPerNode
	}
	return 0
}

func (m *Params) GetMaxTrustScore() int32 {
	if m != nil {
		return m.MaxTrustScore
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "contactical.reality.v1.Params")
}

func init() {
	proto.RegisterFile("contactical/reality/v1/params.proto", fileDescriptor_6500cda98d68c26f)
}

var fileDescriptor_6500cda98d68c26f = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4e, 0x32, 0x41,
	0x14, 0x85, 0x59, 0xf8, 0x21, 0xbf, 0x9b, 0x88, 0xba, 0x1a, 0xb2, 0x01, 0xb3, 0x12, 0x8d, 0x4a,
	0x2c, 0xd8, 0x10, 0x62, 0x63, 0x49, 0x2c, 0x8d, 0x21, 0x80, 0x8d, 0xcd, 0x64, 0x76, 0xf7, 0x86,
	0x6c, 0x60, 0xe7, 0x6e, 0x66, 0x2e, 0xb8, 0xbc, 0x82, 0x95, 0x8f, 0x60, 0xe1, 0x03, 0xf8, 0x18,
	0x96, 0x94, 0x96, 0x06, 0x0a, 0x7d, 0x0c, 0xc3, 0x8c, 0x18, 0x0a, 0x9b, 0xc9, 0xcd, 0x77, 0xbe,
	0x39, 0xc5, 0xb1, 0x4f, 0x42, 0x14, 0xc4, 0x43, 0x8a, 0x43, 0x3e, 0xf6, 0x25, 0xf0, 0x71, 0x4c,
	0x33, 0x7f, 0xda, 0xf2, 0x53, 0x2e, 0x79, 0xa2, 0x9a, 0xa9, 0x44, 0x42, 0xa7, 0xb2, 0x21, 0x35,
	0x7f, 0xa4, 0xe6, 0xb4, 0x55, 0xdd, 0xe3, 0x49, 0x2c, 0xd0, 0xd7, 0xaf, 0x51, 0xab, 0x07, 0x43,
	0x1c, 0xa2, 0x3e, 0xfd, 0xd5, 0x65, 0xe8, 0xf1, 0x4b, 0xde, 0x2e, 0x75, 0x75, 0xa3, 0xd3, 0xb0,
	0x77, 0x25, 0x3c, 0x70, 0x19, 0xb1, 0x80, 0x2b, 0x60, 0x13, 0x11, 0x93, 0x6b, 0xd5, 0xad, 0x46,
	0xa1, 0x57, 0x36, 0xbc, 0xc3, 0x15, 0xdc, 0x89, 0x98, 0x9c, 0x73, 0x7b, 0x27, 0x40, 0x31, 0x51,
	0x4c, 0x91, 0x44, 0x31, 0x0c, 0x30, 0x73, 0xf3, 0x75, 0xab, 0x51, 0xec, 0x95, 0x35, 0xee, 0xaf,
	0xa9, 0x53, 0xb3, 0xb7, 0x8c, 0x48, 0x00, 0x6e, 0x41, 0x2b, 0xff, 0x35, 0x18, 0x00, 0x38, 0x67,
	0xeb, 0x96, 0x00, 0x91, 0xd8, 0x18, 0xc3, 0x91, 0xfb, 0x4f, 0x2b, 0xdb, 0x1a, 0x77, 0x10, 0xe9,
	0x06, 0xc3, 0x91, 0xd3, 0xb6, 0x2b, 0xc6, 0x8b, 0x40, 0xa8, 0x98, 0x66, 0x2c, 0x05, 0xc9, 0x04,
	0x46, 0xe0, 0x16, 0xb5, 0xbe, 0xaf, 0xd3, 0x6b, 0x13, 0x76, 0x41, 0xde, 0x62, 0xa4, 0xcb, 0x13,
	0x9e, 0x31, 0x92, 0x13, 0x45, 0x4c, 0x85, 0x28, 0xc1, 0x2d, 0x99, 0xf2, 0x84, 0x67, 0x83, 0x15,
	0xed, 0xaf, 0xe0, 0xd5, 0xe9, 0xd7, 0xf3, 0x91, 0xf5, 0xf8, 0xf9, 0x7a, 0x71, 0xb8, 0x39, 0x77,
	0xf6, 0x3b, 0xb8, 0xd9, 0xa6, 0x73, 0xf9, 0xb6, 0xf0, 0xac, 0xf9, 0xc2, 0xb3, 0x3e, 0x16, 0x9e,
	0xf5, 0xb4, 0xf4, 0x72, 0xf3, 0xa5, 0x97, 0x7b, 0x5f, 0x7a, 0xb9, 0xfb, 0xda, 0xdf, 0xff, 0x68,
	0x96, 0x82, 0x0a, 0x4a, 0x7a, 0xe4, 0xf6, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xad, 0xbc,
	0xc6, 0xcc, 0x01, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.RewardBaseUnit != that1.RewardBaseUnit {
		return false
	}
	if this.BonusStrongbox != that1.BonusStrongbox {
		return false
	}
	if this.BonusTee != that1.BonusTee {
		return false
	}
	if this.BonusBootLock != that1.BonusBootLock {
		return false
	}
	if this.BonusDensityPerNode != that1.BonusDensityPerNode {
		return false
	}
	if this.MaxTrustScore != that1.MaxTrustScore {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxTrustScore != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxTrustScore))
		i--
		dAtA[i] = 0x30
	}
	if m.BonusDensityPerNode != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BonusDensityPerNode))
		i--
		dAtA[i] = 0x28
	}
	if m.BonusBootLock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BonusBootLock))
		i--
		dAtA[i] = 0x20
	}
	if m.BonusTee != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BonusTee))
		i--
		dAtA[i] = 0x18
	}
	if m.BonusStrongbox != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BonusStrongbox))
		i--
		dAtA[i] = 0x10
	}
	if m.RewardBaseUnit != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RewardBaseUnit))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RewardBaseUnit != 0 {
		n += 1 + sovParams(uint64(m.RewardBaseUnit))
	}
	if m.BonusStrongbox != 0 {
		n += 1 + sovParams(uint64(m.BonusStrongbox))
	}
	if m.BonusTee != 0 {
		n += 1 + sovParams(uint64(m.BonusTee))
	}
	if m.BonusBootLock != 0 {
		n += 1 + sovParams(uint64(m.BonusBootLock))
	}
	if m.BonusDensityPerNode != 0 {
		n += 1 + sovParams(uint64(m.BonusDensityPerNode))
	}
	if m.MaxTrustScore != 0 {
		n += 1 + sovParams(uint64(m.MaxTrustScore))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardBaseUnit", wireType)
			}
			m.RewardBaseUnit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RewardBaseUnit |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BonusStrongbox", wireType)
			}
			m.BonusStrongbox = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BonusStrongbox |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BonusTee", wireType)
			}
			m.BonusTee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BonusTee |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BonusBootLock", wireType)
			}
			m.BonusBootLock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BonusBootLock |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BonusDensityPerNode", wireType)
			}
			m.BonusDensityPerNode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BonusDensityPerNode |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTrustScore", wireType)
			}
			m.MaxTrustScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTrustScore |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
