// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: contactical.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContacticalService_RegisterNode_FullMethodName = "/contactical.v1.ContacticalService/RegisterNode"
	ContacticalService_SubmitData_FullMethodName   = "/contactical.v1.ContacticalService/SubmitData"
)

// ContacticalServiceClient is the client API for ContacticalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 1. 서비스 정의: 서버가 제공할 기능들의 목록
type ContacticalServiceClient interface {
	// 노드 등록 (Key Attestation 검증 포함)
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	// 센서 데이터 제출 (TEE 서명 검증 포함)
	SubmitData(ctx context.Context, in *SubmitDataRequest, opts ...grpc.CallOption) (*SubmitDataResponse, error)
}

type contacticalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContacticalServiceClient(cc grpc.ClientConnInterface) ContacticalServiceClient {
	return &contacticalServiceClient{cc}
}

func (c *contacticalServiceClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, ContacticalService_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contacticalServiceClient) SubmitData(ctx context.Context, in *SubmitDataRequest, opts ...grpc.CallOption) (*SubmitDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitDataResponse)
	err := c.cc.Invoke(ctx, ContacticalService_SubmitData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContacticalServiceServer is the server API for ContacticalService service.
// All implementations must embed UnimplementedContacticalServiceServer
// for forward compatibility.
//
// 1. 서비스 정의: 서버가 제공할 기능들의 목록
type ContacticalServiceServer interface {
	// 노드 등록 (Key Attestation 검증 포함)
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	// 센서 데이터 제출 (TEE 서명 검증 포함)
	SubmitData(context.Context, *SubmitDataRequest) (*SubmitDataResponse, error)
	mustEmbedUnimplementedContacticalServiceServer()
}

// UnimplementedContacticalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContacticalServiceServer struct{}

func (UnimplementedContacticalServiceServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedContacticalServiceServer) SubmitData(context.Context, *SubmitDataRequest) (*SubmitDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitData not implemented")
}
func (UnimplementedContacticalServiceServer) mustEmbedUnimplementedContacticalServiceServer() {}
func (UnimplementedContacticalServiceServer) testEmbeddedByValue()                            {}

// UnsafeContacticalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContacticalServiceServer will
// result in compilation errors.
type UnsafeContacticalServiceServer interface {
	mustEmbedUnimplementedContacticalServiceServer()
}

func RegisterContacticalServiceServer(s grpc.ServiceRegistrar, srv ContacticalServiceServer) {
	// If the following call panics, it indicates UnimplementedContacticalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContacticalService_ServiceDesc, srv)
}

func _ContacticalService_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContacticalServiceServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContacticalService_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContacticalServiceServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContacticalService_SubmitData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContacticalServiceServer).SubmitData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContacticalService_SubmitData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContacticalServiceServer).SubmitData(ctx, req.(*SubmitDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContacticalService_ServiceDesc is the grpc.ServiceDesc for ContacticalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContacticalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contactical.v1.ContacticalService",
	HandlerType: (*ContacticalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _ContacticalService_RegisterNode_Handler,
		},
		{
			MethodName: "SubmitData",
			Handler:    _ContacticalService_SubmitData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contactical.proto",
}
