// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: contactical.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 노드 등록 요청
type RegisterNodeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CreatorAddress string                 `protobuf:"bytes,1,opt,name=creator_address,json=creatorAddress,proto3" json:"creator_address,omitempty"` // 사용자의 지갑 주소
	CertChain      []string               `protobuf:"bytes,2,rep,name=cert_chain,json=certChain,proto3" json:"cert_chain,omitempty"`                // Android에서 보낸 인증서 체인 (Base64 리스트)
	Challenge      string                 `protobuf:"bytes,3,opt,name=challenge,proto3" json:"challenge,omitempty"`                                 // 서버에서 받은 챌린지 값
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_contactical_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contactical_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_contactical_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetCreatorAddress() string {
	if x != nil {
		return x.CreatorAddress
	}
	return ""
}

func (x *RegisterNodeRequest) GetCertChain() []string {
	if x != nil {
		return x.CertChain
	}
	return nil
}

func (x *RegisterNodeRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // 등록 성공 시 부여되는 고유 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_contactical_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contactical_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_contactical_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// 데이터 제출 요청
type SubmitDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // 등록된 노드 ID
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`             // 실제 데이터 (예: "lat: 37.5, lon: 127.0")
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`         // TEE로 만든 서명 (Base64)
	Cert          string                 `protobuf:"bytes,4,opt,name=cert,proto3" json:"cert,omitempty"`                   // (선택) 검증을 위한 리프 인증서
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDataRequest) Reset() {
	*x = SubmitDataRequest{}
	mi := &file_contactical_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDataRequest) ProtoMessage() {}

func (x *SubmitDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contactical_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDataRequest.ProtoReflect.Descriptor instead.
func (*SubmitDataRequest) Descriptor() ([]byte, []int) {
	return file_contactical_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitDataRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SubmitDataRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *SubmitDataRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SubmitDataRequest) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

type SubmitDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"` // 블록체인에 기록된 트랜잭션 해시
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDataResponse) Reset() {
	*x = SubmitDataResponse{}
	mi := &file_contactical_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDataResponse) ProtoMessage() {}

func (x *SubmitDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contactical_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDataResponse.ProtoReflect.Descriptor instead.
func (*SubmitDataResponse) Descriptor() ([]byte, []int) {
	return file_contactical_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitDataResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

var File_contactical_proto protoreflect.FileDescriptor

const file_contactical_proto_rawDesc = "" +
	"\n" +
	"\x11contactical.proto\x12\x0econtactical.v1\"{\n" +
	"\x13RegisterNodeRequest\x12'\n" +
	"\x0fcreator_address\x18\x01 \x01(\tR\x0ecreatorAddress\x12\x1d\n" +
	"\n" +
	"cert_chain\x18\x02 \x03(\tR\tcertChain\x12\x1c\n" +
	"\tchallenge\x18\x03 \x01(\tR\tchallenge\"c\n" +
	"\x14RegisterNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\"x\n" +
	"\x11SubmitDataRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12\x12\n" +
	"\x04cert\x18\x04 \x01(\tR\x04cert\"G\n" +
	"\x12SubmitDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash2\xc4\x01\n" +
	"\x12ContacticalService\x12Y\n" +
	"\fRegisterNode\x12#.contactical.v1.RegisterNodeRequest\x1a$.contactical.v1.RegisterNodeResponse\x12S\n" +
	"\n" +
	"SubmitData\x12!.contactical.v1.SubmitDataRequest\x1a\".contactical.v1.SubmitDataResponseB\x14Z\x12contactical/api/v1b\x06proto3"

var (
	file_contactical_proto_rawDescOnce sync.Once
	file_contactical_proto_rawDescData []byte
)

func file_contactical_proto_rawDescGZIP() []byte {
	file_contactical_proto_rawDescOnce.Do(func() {
		file_contactical_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contactical_proto_rawDesc), len(file_contactical_proto_rawDesc)))
	})
	return file_contactical_proto_rawDescData
}

var file_contactical_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_contactical_proto_goTypes = []any{
	(*RegisterNodeRequest)(nil),  // 0: contactical.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil), // 1: contactical.v1.RegisterNodeResponse
	(*SubmitDataRequest)(nil),    // 2: contactical.v1.SubmitDataRequest
	(*SubmitDataResponse)(nil),   // 3: contactical.v1.SubmitDataResponse
}
var file_contactical_proto_depIdxs = []int32{
	0, // 0: contactical.v1.ContacticalService.RegisterNode:input_type -> contactical.v1.RegisterNodeRequest
	2, // 1: contactical.v1.ContacticalService.SubmitData:input_type -> contactical.v1.SubmitDataRequest
	1, // 2: contactical.v1.ContacticalService.RegisterNode:output_type -> contactical.v1.RegisterNodeResponse
	3, // 3: contactical.v1.ContacticalService.SubmitData:output_type -> contactical.v1.SubmitDataResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contactical_proto_init() }
func file_contactical_proto_init() {
	if File_contactical_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contactical_proto_rawDesc), len(file_contactical_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contactical_proto_goTypes,
		DependencyIndexes: file_contactical_proto_depIdxs,
		MessageInfos:      file_contactical_proto_msgTypes,
	}.Build()
	File_contactical_proto = out.File
	file_contactical_proto_goTypes = nil
	file_contactical_proto_depIdxs = nil
}
